{% set name = "ipyopt" %}
{% set version = "0.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e130a29d235a7fa1fb55df4bac60586f8c7c79df4c99bd1ad0ebc6e9e52c2c10

build:
  number: 0
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - python
    - ipopt
    - numpy 1.14
    - pip
  run:
    - python
    - {{ pin_compatible('ipopt') }}
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - examples
  imports:
    - ipyopt
  commands:
    - python examples/hs071.py

about:
  home: https://github.com/g-braeunlich/IPyOpt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for IPOPT

  description: |
    IPyOpt is a python module that allows you to use
    IPOPT (http://www.coin-or.org/Ipopt/) in Python.
    It was developed by Eric Xu when he was a PhD student at Washington
    University.
    Original repository: https://github.com/xuy/pyipopt.
  dev_url: https://github.com/g-braeunlich/IPyOpt

extra:
  recipe-maintainers:
    - minrk
