{% set name = "ipyopt" %}
{% set version = "0.12.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b841f319d7af1ecfd93dc59ff3b65d51d01a59c9f59d7dc3bb2bd42604efd84

build:
  number: 2
  skip: true  # [win or py2k]
  script:
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
    # setuptools still ignores CXX env and uses C instead
    - export CFLAGS=$CXXFLAGS
    - export CC=$CXX
    - {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - ipopt
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('ipopt') }}
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - examples
  imports:
    - ipyopt
  commands:
    - python examples/hs071.py

about:
  home: https://github.com/g-braeunlich/IPyOpt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for IPOPT

  description: |
    IPyOpt is a python module that allows you to use
    IPOPT (http://www.coin-or.org/Ipopt/) in Python.
    It was developed by Eric Xu when he was a PhD student at Washington
    University.
    Original repository: https://github.com/xuy/pyipopt.
  dev_url: https://gitlab.com/g-braeunlich/ipyopt

extra:
  recipe-maintainers:
    - traversaro
    - minrk
